import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import type { CommandAction, CommandMeta, CommandOptions } from "@buttery/cli";
import { getButteryConfig } from "@buttery/core";
import { createGraph } from "./_utils/util.createGraph";
import { getDocsDir } from "./_utils/util.getDocsDir";
import { LOG_DOCS } from "./_utils/util.logger";

export const meta: CommandMeta = {
  name: "build",
  description:
    "Build the necessary assets required to create actions, fetchers, and components to render the Buttery Docs template."
};

export const options: CommandOptions<"watch"> = {
  watch: {
    alias: "w",
    description: "Run the build in watch mode",
    type: "boolean",
    required: false
  }
};

export const action: CommandAction<typeof options> = async ({ options }) => {
  try {
    const configs = await getButteryConfig("docs");
    const butteryDocsDirPath = getDocsDir(configs.configBase, configs.docs);
    const docsGraph = await createGraph({ docsDir: butteryDocsDirPath });

    // create the directory for .buttery-docs
    LOG_DOCS.debug("Creating .buttery-docs directory...");
    const dotButteryDocsDirPath = path.resolve(
      configs.configBase.root,
      "./.buttery-docs"
    );
    await mkdir(dotButteryDocsDirPath, { recursive: true });
    LOG_DOCS.debug("Creating .buttery-docs directory... done.");

    // write the graph to the graph file
    LOG_DOCS.debug("Writing the graph to the __graph.ts file...");
    const graphPath = path.resolve(dotButteryDocsDirPath, "./__graph.ts");
    const graphContent = `import type { ButteryDocsGraph } from "@buttery/docs/types";
 
export const graph: ButteryDocsGraph = ${JSON.stringify(docsGraph, null, 2)};
`;
    await writeFile(graphPath, graphContent);
    LOG_DOCS.debug("Writing the graph to the __graph.ts file... done.");

    // TODO: Break this out into another file
    // write the barrel file
    LOG_DOCS.debug("Writing barrel file for easy route export syntax...");
    const barrelPath = path.resolve(dotButteryDocsDirPath, "./index.tsx");
    const barrelContent = `// THIS FILE IS AUTO GENERATED BY \`@BUTTERY/DOCS\`. PLEASE DO NOT EDIT
import "@buttery/tokens/_docs/index.css"
import "@buttery/docs/css";
import { createRoute } from "@buttery/docs/remix/cloudflare";
import { graph } from "./__graph";

export const route = createRoute(graph);
`;
    await writeFile(barrelPath, barrelContent);
    LOG_DOCS.debug("Writing barrel file for easy route export syntax... done.");
    LOG_DOCS.success("Build complete.");
  } catch (error) {
    console.log(error);
    throw LOG_DOCS.fatal(new Error(error as string));
  }
};
