// THIS FILE IS AUTO GENERATED BY @BUTTERY/DOCS. PLEASE DO NOT EDIT

import { createRoute } from "@buttery/docs/remix/cloudflare";
import { graph } from "./__graph";

const route = createRoute(graph);

export const { meta, loader } = route;
export default route.page;

