import { writeFile } from "node:fs/promises";
import path from "node:path";
import type { ButteryConfigBase, ButteryConfigDocsRemix } from "@buttery/core";
import { glob } from "glob";
import { createGraph } from "../util.createGraph";
import { LOG_DOCS } from "../util.logger";

export async function buildRemix(
  baseConfig: ButteryConfigBase,
  docsConfig: ButteryConfigDocsRemix
): Promise<void> {
  const remixRoutesDir = path.resolve(baseConfig.root, "./app/routes/");
  const patterns = [
    `**/${docsConfig.docsPrefix}/**/*`,
    `**/${docsConfig.docsPrefix}.*`
  ].map((pattern) => path.resolve(remixRoutesDir, pattern));

  const files = await glob(patterns);

  const docsGraph = await createGraph({
    files
  });

  LOG_DOCS.debug("Creating resource route...");
  const resourceRoutePath = path.resolve(remixRoutesDir, "./api.docs.graph.ts");
  const resourceRouteContent = `// THIS FILE IS AUTO GENERATED BY \`@BUTTERY/DOCS\`. PLEASE DO NOT EDIT
import type { ButteryDocsGraph } from "@buttery/docs/types";
import { json } from "@remix-run/cloudflare";

const graph: ButteryDocsGraph = ${JSON.stringify(docsGraph, null, 2)}

/**
 * A loader that can either be imported as an alias and then re-exported
 * or straight up re-exported to be used in any route that only requires
 * the documentation graph
 */
export async function loader() {
  return json({ graph });
}

/**
 * A standalone function that fetches the graph from the loader that is defined
 * in this resource route.
 */
export async function getGraph(request: Request) {
  try {
    const requestURL = new URL(request.url);
    const res = await fetch(requestURL.origin.concat("/api/docs/graph"));
    const data = (await res.json()) as ButteryDocsGraph;
    return data;
  } catch (error) {
    throw new Response(
      \`There was an error when trying to fetch the documentation graph: \${error}\`,
      { status: 500 }
    );
  }
}
`;
  await writeFile(resourceRoutePath, resourceRouteContent);
  LOG_DOCS.debug("Creating resource route... done.");
}
